### ISSUE TITLE
get rid of the topsect option in notesslides.cls

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX#288]
We have to use 
```
\documentclass[slides,class=book,topsect=chapter]{notesslides}  
```
instead of the more intuitive
```
\documentclass[slides,class=book]{notesslides}  
```
because otherwise beamer does not find the chapter counter. 
But `topsect=chapter` should really be induced by `class=book`. This seems to be a left-over peculiarity of sTeX1

**Comment by Jazzpirate** [comment]
shouldn't the topsect for book be "part" rather than "chapter"? Either way, the two options exist, so I don't think it's a good idea to force one or the other merely based on the class...

(I did find a typo in the code though, so that would have broken things). What currently (soon, after a push) happens is that if the class is `book` and no topsect is set, the the topsect is part(!), otherwise the (default) topsect is section. That looks right to me...?

**Comment by kohlhase** [comment]
> ..., the two options exist, so I don't think it's a good idea to force one or the other merely based on the class...

I think the option only existed, since I could not get the topsect inference to work properly :-( I guess I did not find the typo).

**Comment by Jazzpirate** [comment]
> I think the option only existed, since I could not get the topsect inference to work properly :-( I guess I did not find the typo).

Sorry, by "the two options" I meant "part" and "chapter" in the case of `class=book`. Point being, that depending on the use case the intended topsect it could be either of the two, so I think it's a good idea to leave `topsect` as a package/class option so that users can choose between (at least) the two.

**Comment by kohlhase** [comment]
you are right. I did try it without the `topsect=chapter` and that is not what I wanted. 

BTW, Then I get 
"PartI" and "Chapter1" (missing blank) in the `sectocframe`s 
Maybe that can still be fixed.

**Comment by kohlhase** [comment]
works. thanks.
