### ISSUE TITLE
Exam whitespace (\testnewpage and \testemptypage) not working properly

### ISSUE THREAD

**Issue by lambdaTotoro** [slatex/sTeX#364]
Pretty much exactly what it says on the tin. We're having retakes soon and currently, when I `pdflatex` the retake for IWGS, the `\testnewpage` and `\testemptypage` commands don't actually get translated into whitespace.

/cc @kohlhase

**Comment by Jazzpirate** [comment]
Do you have an example document I can try out pushed somewhere?

**Comment by Jazzpirate** [comment]
Turns out:
1. \testnewpage and \testemptypage do nothing unless the package option `boxed` is given (for hwexam or problem). I'm not entirely sure what it does or why it even exists, but adding the package option solves your problem
2. I found another bug in \testemptypage and while fixing it also rewrote it so that the text "This page was intentionally left empty" is set at the *bottom* of the page rather than at the top. I vaguely remember there being discussions that otherwise it might be confusing to students. (See d1d76297ec5c0e4055f5f6c8bd55f4bb7df5464a)

**Comment by lambdaTotoro** [comment]
Thank you, das funktioniert. Jetzt ist der Whitespace aber überall, auch im `retake-with-solutions.pdf`. Gibt es etwas, was ich dort im tex eintragen kann, damit der Whitespace wieder verschwindet?

**Comment by Jazzpirate** [comment]
hmm, hast du mal `boxed=false` versucht? Aber ehrlich gesagt bin ich jetzt am raten. Keine ahnung was die *intention* hinter dem `boxed` war oder warum ausgerechnet *das* bestimmt ob newpages was tun... 0o

**Comment by lambdaTotoro** [comment]
Guess or not, it works! Thank you! =)
