### ISSUE TITLE
leftover overlay specifications

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX#376]
On https://courses.voll-ki.fau.de/browser/%3AsTeX%2Fdocument%3Farchive%3DMiKoMH%2FAI%26filepath%3Dcourse%2Fnotes%2Fnotes.xhtml?inDocPath=-to8f9d.i4m5qz.mnzbzh.-wgxq4l I see 
<img width="911" alt="Screenshot 2022-11-03 at 19 52 07" src="https://user-images.githubusercontent.com/4037538/199809577-0d953c45-4b22-40a6-93d1-6321a3c3664f.png">
there seem to be some beamer overlay specifications left over.

**Comment by kohlhase** [comment]
Oh, and the font sizes and dimensions seem be quite off. We should have done that update on a staging server first.

**Comment by Jazzpirate** [comment]
Actually no, that makes sense and to some degree indicates that we need a third variant of `\mhinput`/`\inputref` we should think about: The sources in the smglom themselves (https://gl.mathhub.info/smglom/grammar/-/blob/main/source/mod/grammar-types.en.tex) do contain the `\item <i->`, but don't have a `frame` where that would make sense - hence `grammar-types.en.pdf` should have the same problem as the HTML. Except of course that the pdf of the *notes* don't have that problem, because there the smglom-tex is `\input` inside a `frame` anyway.

In the HTML of the notes however, the smglom HTML is inserted as (basically) an `<iframe>` - so you get the exact same formatting and typesetting in the notes as in the smglom entry itself.

**Comment by Jazzpirate** [comment]
Although I don't know what a new `mhinput`-like macro would look like - these problems seem to me unavoidable if one wants the html files to be modular... :/

**Comment by kohlhase** [comment]
You are completely right, this is a content error on my part (sorry to have bothered you with this; I did not have time to check in depth with all the teaching yesterday). I think there is no way a new \input could fix this. Overlay specifications have no place in smglom! I will rework this.

**Comment by Jazzpirate** [comment]
I think we can do something about the font sizes and dimensions though (see the sTeX-React-channel on mattermost)...

**Comment by kohlhase** [comment]
Yes I saw, sounds very promising.
