### ISSUE TITLE
varseq should not have index-expressions bracketed 

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX#430]
I get the following 
<img width="439" alt="Screenshot 2024-11-07 at 10 41 06" src="https://github.com/user-attachments/assets/96bd1a34-1d53-47e5-95c7-8f4c86b6d3c1">
in the PDF (and I guess in the HTML as well) generate from 
```
\varseq{seqs}{1,\ellipses,n}{\comp{s}_{#1}}
...  to \sn{state} $\seqs{\natminus{i,1}}$, where $\inset{\seqs0}\initial$, ....
```
 I would have expoted `$s_{i-1}$` straight; i.e. without brackets. The reason being that we do not need brackets in indexes because they are already "delimited" their position (and mathematicians tend to do it this way).

**Comment by Jazzpirate** [comment]
That is a property of the notation used (in this case, the one of `seqs`). sTeX does and can not "know" that the index occurs in a subscript that does not need brackets - it compares precedences; in this case the argument-precedence of `seqs` and the operator precedence of `\natminus`. Since the former isn't set, its default value is 0. So either
- set a more reasonable argument precedence for the first argument of `seqs`, or
- set a different operator precedence for `\natminus`

**Comment by kohlhase** [comment]
the second is not really an option. How do I do the first?

**Comment by Jazzpirate** [comment]
`\varseq{seqs}[prec=nobrackets]{1,\ellipses,n}{\comp{s}_{#1}}` should do it, but may or may not be what you want. More explicitly and controllably: `prec={<operator-precedence>;<argument-precedence>}`

**Comment by kohlhase** [comment]
ah, I was not aware (and it is not documented in the tutorial) that `\varseq` takes a `prec=` attribute. Very cool and obvious in hindsigt.

**Comment by Jazzpirate** [comment]
Fair. "Internally", it really is obvious: A `\varseq` is ultimately just a `\vardef`, which just delegates to `\varnotation`, which just delegates to `\notation`. As such, the presentation of variable sequences is exactly as controllable as are those of variables, as are those of any other symbol.

**Comment by kohlhase** [comment]
I still maintain, the documentation should have a line saying: \varseq takes  all the optional arguments that \notation does. And then add a precedence example :-)

**Comment by Jazzpirate** [comment]
Fine by me, given that the documentation will need a complete overhaul anyway :D
